name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: make install-dependencies

      # - name: Install ginkgo bin
      #   run: go get github.com/onsi/ginkgo/v2/ginkgo

      - name: Run tests
        run: make test
